# Generated by Django 5.0.4 on 2024-05-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transaction_type', models.CharField(max_length=255)),
                ('num', models.CharField(max_length=255)),
                ('posting', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('memo_description', models.CharField(max_length=255)),
                ('account', models.CharField(max_length=255)),
                ('split', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
            ],
        ),
    ]
